import { Nunito } from "next/font/google";
import "./globals.css";
import TopBar from "./components/TopBar";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Anet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} bg-blue-50 flex flex-col overflow-y-scroll`}>
        <header className="backdrop-blur-md bg-blue-100/50 flex w-full h-content sticky top-0 ml-5 mr-5 rounded-b-2xl">
          <TopBar/>
        </header>
        <main className="flex w-full bg-white justify-center">{children}</main>
      </body>
    </html>
  );
}
