import { Nunito } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import TopBar from "./components/TopBar";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Anet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <body className={`${nunito.className} flex flex-col bg-white overflow-y-scroll`}>
        <header className="flex w-full h-content sticky top-0 backdrop-blur-xl bg-blue-100/20">
          <TopBar/>
        </header>
        <main className="flex w-full bg-white">{children}</main>
      </body>
    </html>
  );
}
